version: '3.8'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgres://root:root@db:5432/jq_laravel
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jq_laravel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
